# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param N the number of samples
#' @param thin the number of between-sample random numbers
#' @param n a parameter of the binomial distribution
#' @param a a parameter of the beta df
#' @param b a parameter of the beta df
#' @return a random sample of size \code{n}
#' @examples
#' \dontrun{
#'   rnC <- gibbsC(100,10)
#' }
#' @export
gibbsC <- function(N, thin, n, a, b) {
    .Call('_StatComp21037_gibbsC', PACKAGE = 'StatComp21037', N, thin, n, a, b)
}

